# Generated by Django 2.0.5 on 2019-12-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback1Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Rating', models.IntegerField()),
                ('Mobile', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=100)),
                ('Date', models.DateTimeField()),
                ('Feeback', models.TextField(max_length=100)),
            ],
        ),
    ]
