# Generated by Django 2.0.5 on 2019-12-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback1app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback1data',
            old_name='Feeback',
            new_name='feeb',
        ),
    ]
